---
       
- hosts: vm
  gather_facts: false
  connection: local

  tasks:
    
    - name: Find all template files for tests
      find:
        paths: "{{ terraform_test_template_dir }}/"        
        patterns: '*.j2'
        file_type: file
      register: terraform_test_templates
    
    - name: Create terraform test files      
      template: 
        src: "{{ file.path }}"
        dest: "{{ terraform_test_output_dir }}/{{ inventory_hostname }}_{{ file.path | basename | replace('.j2','') }}"
      delegate_to: localhost
      with_items: "{{ terraform_test_templates.files }}"
      loop_control:
        loop_var: file
      when:
        - terraform_test_templates is defined
        - terraform_test_templates.files | length > 0

- hosts: localhost
  gather_facts: false
  connection: local

  tasks:

    - set_fact:
        terraform_command: >
          docker run --rm -i
          -v {{ terraform_test_output_dir }}:/data
          -v {{ terraform_module_output_dir }}:/module
          {{ terraform_deployment_image }}

    - debug: var=terraform_command

    - name: Capturing terraform fmt
      command: "{{ terraform_command }} fmt ."
      register: terraform_fmt_state
      changed_when: false
      args:
        chdir: "{{ terraform_test_output_dir }}"

    - name: Debug terraform fmt
      debug: var=terraform_fmt_state.stderr
      when:
        - terraform_fmt_state.rc > 0

    - name: Capturing terraform Init
      command: "{{ terraform_command }} init -no-color"
      register: terraform_init_state
      changed_when: false
      args:
        chdir: "{{ terraform_test_output_dir }}"

    - name: Debug terraform init
      debug: var=terraform_init_state.stderr
      when:
        - terraform_init_state.rc > 0

    - name: Capturing terraform validate
      command: "{{ terraform_command }} validate"
      register: terraform_validate_state
      changed_when: false
      args:
        chdir: "{{ terraform_test_output_dir }}"

    - name: Debug terraform validate
      debug: var=terraform_validate_state.stderr
      when:
        - terraform_validate_state.rc > 0
