---

- hosts: vm
  gather_facts: false

  vars:
    ansible_ssh_port: "{{ sshd_port }}"
    ansible_ssh_user: core
    ansible_python_interpreter: /opt/bin/python

  pre_tasks:

    - name: "Wait for port {{ sshd_port }} to become open on the host, don't start checking for 20 seconds"
      wait_for:
        timeout: 300
        port: "{{ sshd_port }}"
        delay: 60

  tasks:

    # Induce an exception to see what happens
    - ping:

    - name: "Searching for Flatcar Linux"
      become: yes
      become_user: root      
      lineinfile:
        path: /etc/os-release
        line: "ID=flatcar"
        state: present
      check_mode: yes
      failed_when: presence is changed
      register: presence
