---

- hosts: localhost
  gather_facts: false
  connection: local

  tasks:

    - set_fact:
        terraform_command: >
          docker run --rm -i
          -v {{ terraform_test_output_dir }}:/data
          -v {{ terraform_module_output_dir }}:/module  
          {{ terraform_deployment_image }}
    
    - name: Apply terraform plan
      command: "{{ terraform_command }} apply -input=false -auto-approve -no-color /data/tfplan"
      register: terraform_apply_state
      changed_when: false
      args:
        chdir: "{{ terraform_test_output_dir }}"

    - set_stats:
        data:
          terraform_apply_state: "{{ terraform_apply_state.stdout_lines }}"

