---

- hosts: vm
  gather_facts: true  

  vars:
    ansible_ssh_port: "{{ sshd_port }}"
    ansible_ssh_user: core
    ansible_python_interpreter: /opt/bin/python

  tasks:
    
    # Induce an exception to see what happens
    - ping: