---

- hosts: vm
  gather_facts: true  

  vars:
    ansible_ssh_port: "{{ sshd_port }}"
    ansible_ssh_user: core
    ansible_python_interpreter: /opt/bin/python

  tasks:

    # Induce an exception to see what happens
    - ping:

    - name: "Searching for Flatcar Linux"
      become: yes
      become_user: root      
      lineinfile:
        path: /etc/os-release
        line: "ID=flatcar"
        state: present
      check_mode: yes
      failed_when: presence is changed
      register: presence
